name: Build FrankenPHP with Souin

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permet de déclencher manuellement le workflow

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PHP_VERSION: 8.3
      # Définissez le nom du tag de votre release ici, par exemple 'latest'
      RELEASE_TAG: main # Ou 'latest' si vous préférez un tag plus générique pour la dernière build
      RELEASE_NAME: Latest Main Build
      ASSET_NAME: frankenphp # Nom de l'asset à uploader
      ASSET_PATH: ./frankenphp # Chemin local de l'asset

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build FrankenPHP Docker image
        id: build_image
        run: |
          docker build --target builder --build-arg PHP_VERSION=${{ env.PHP_VERSION }} -t frankenphp-builder .
          CONTAINER_ID=$(docker create frankenphp-builder)
          docker cp $CONTAINER_ID:/usr/local/bin/frankenphp ${{ env.ASSET_PATH }}
          docker rm $CONTAINER_ID
          chmod +x ${{ env.ASSET_PATH }}

      - name: Create or Update Release and Upload Asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_NAME }}
          body: FrankenPHP binary built from main branch
          draft: false
          prerelease: false
          files: ${{ env.ASSET_PATH }} # Spécifiez le chemin de l'asset à uploader
          overwrite: true # Cette option est cruciale pour remplacer les assets existants
