name: Build FrankenPHP with Souin

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permet de déclencher manuellement le workflow

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PHP_VERSION: 8.3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build FrankenPHP Docker image
        id: build_image
        run: |
          # Construit l'image Docker, en se concentrant sur l'étape 'franken-builder'
          docker build --target builder --build-arg PHP_VERSION=${{ env.PHP_VERSION }} -t frankenphp-builder .
          
          # Crée un conteneur temporaire à partir de l'image construite
          CONTAINER_ID=$(docker create frankenphp-builder)
          
          # Copie le binaire depuis le conteneur vers le runner
          docker cp $CONTAINER_ID:/usr/local/bin/frankenphp ./frankenphp_with_souin
          
          # Supprime le conteneur temporaire
          docker rm $CONTAINER_ID
          
          # Rend le binaire exécutable (important pour la prochaine étape)
          chmod +x ./frankenphp_with_souin

      - name: Upload FrankenPHP binary as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: frankenphp-binary
          path: ./frankenphp_with_souin
          # Optionnel: définir une expiration si vous ne voulez pas les garder indéfiniment
          # retention-days: 7

      - name: Create GitHub Release (or push to S3/GCS)
        # Cette étape dépendra de l'endroit où vous voulez stocker le binaire
        # Pour une release GitHub:
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') # Déclenche une release uniquement sur les tags
        with:
          files: ./frankenphp_with_souin
          name: FrankenPHP with Souin ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          draft: true # Optionnel: crée un brouillon de release
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token fourni automatiquement par GitHub Actions
